### PR TITLE
Fix chef_gem compat for Chef 12.1.0

### PR DESCRIPTION
**Pull request by juliandunn**
Per https://www.chef.io/blog/2015/03/03/chef-12-1-0-released/

@someara @jdmundrawala

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1: What's the chef 13 fix for this?

**Comment by juliandunn** [comment]
@jdmundrawala sorry I don't know what you mean by that?

**Comment by jdmundrawala** [comment]
```
[2015-02-06T13:27:35-08:00] WARN: setting chef_gem_compile_time to true is deprecated
```

**Comment by juliandunn** [comment]
That's a good question. How are we going to install gems at compile time in Chef 13?

**Pull request merged**
